spring:
  application:
    name: security

  profiles:
    active: dev

  config:
    import: configserver:http://${CONFIG_SERVER_ADDRESS}

  cloud:
    config:
      fail-fast: true

#to config server
redirect:
  prefix: ${LOCALHOST_GATEWAY_ADDRESS}

custom:
  kafka:
    address: ${KAFKA_ADDRESS}
    topic:
      request: ${TOPIC_REQUEST}
      response: ${TOPIC_RESPONSE}
